### ISSUE TITLE
GoSocial development

### ISSUE THREAD

**Issue by yihsuanhung** [yihsuanhung/go-social#2]
## Setting up project infra

Stage 1

  - [x] Setting up Go project #5
  - [x] Setting up db connection #3 
  - [ ] Setting up Go http service #8

Stage 2

- [ ] Setting up env

## 功能開發
  - [ ]  1. 帳號
    - [ ] 1-1. 註冊
    - [ ] 1-2. 登入
  - [ ] 2. 文章 Article
  - [ ] 3. 相簿 Albums

---
